### ISSUE TITLE
bug: Can't improve priority by adding tip to broadcasting transaction.

### ISSUE THREAD

**Issue by foolstack-omg** [availproject/avail#599] opened 2024-06-07 08:25 UTC
# Bug Report

Check the [contributing guide](https://github.com/availproject/avail/blob/main/.github/CONTRIBUTING.md)

## Description

I can't improve priority by adding tip to replace a tipped pending transaction.

## Steps to Reproduce

1. sending a transaction which tip is set to 100, and nonce is set to 1
2. monitor the transaction being sent to the txpool with the pendingExtrinsics rpc function.
3. set the new transaction' tip to 200, and nonce is set to 1
4. Error return by the rpc: Priority is too low: (18446744073709551615 vs 18446744073709551615): The transaction has too low priority to replace another transaction already in the pool.
5. if I set the tip to 0 at the first step, I can replace the transaction with a higher tip. In this situation, it works fine.

## Expected Behavior

I can improve priority of the transaction in the tx pool by add more tip.

## Actual Behavior

Actually, if one add 1 tip to a transaction, its priority is already set to 2^64 - 1, which is the maximum value of uint64. 

## Additional Information

rpc url: wss://turing-rpc.avail.so/ws
npm package: avail-js-sdk

**Comment by Leouarz** [comment] 2024-06-07 15:04
Hey, thank you for opening this issue, it's indeed an unwanted behaviour due to safe overflows.

In polkadot, the DOT has 12 decimals but the AVAIL has 18.
The tip being of this type can overflow with that many decimals. Here's how the calculation will look like in comparison : 

```
WITH AVAIL AND OUR 18 UNITS

max weight       =           2,000,000,000,000
weight           =              20,000,000,000
max tx per block =                         100
tip              =   1,000,000,000,000,000,001
scaled_tip       = 100,000,000,000,000,000,100 <-- OVERFLOW
max u64          =  18,446,744,073,709,551,615 <-- Will return this value




WITH POLKADOT AND THEIR 12 UNITS

max weight       =           2,000,000,000,000
weight           =              20,000,000,000
max tx per block =                         100
tip              =           1,000,000,000,001
scaled_tip       =         100,000,000,000,100 <-- Will return this value
max u64          =  18,446,744,073,709,551,615
```

Solution to this issue are in the corresponding PRs : 
- https://github.com/availproject/polkadot-sdk/pull/10
- https://github.com/availproject/avail-core/pull/98
- https://github.com/availproject/avail/pull/601

**Comment by foolstack-omg** [comment] 2024-06-07 15:45
In the next version, how much tip I set to the transaction, will be the highest priority? 100,000,000,000,000,000,100?

**Comment by Leouarz** [comment] 2024-06-07 15:59
Well you can put any tip you want it should be linear so you can even put 1M avail as tip and it will work as intended. Howere is there a particular reason to add tip ? It should be used only to override a tx or when the network is jammed which won't happen soon.

**Comment by foolstack-omg** [comment] 2024-06-09 01:50
yes, I am using it to override a tx. Because my mnemonic is exposed. I would like to monitor the txpool so that I can override the tx if it exists.

**Comment by Leouarz** [comment] 2024-06-10 08:49
The pull request has been merged, will be on the next update.

**Closed by Leouarz** 2024-06-10 08:49 UTC
Labels: bug
